### ISSUE TITLE
用户分布图的优化

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org.v1#15]
- [x] 响应式，适配小屏幕
- [x] 搞清楚街景模式无法在国内使用的原因
- [x] 增加标题
- [ ] 最近更新时间（是否有可能自动）？
- [ ] 优化icon
- [ ] 定位访问者位置，以不同颜色表示
- [x] 写脚本生成json文件（google map似乎对json格式要求非常严格）？
- [ ] 新建一个全屏的页面放google地图？
- [ ] 一键提交经纬度？
- [ ] 搜索功能？

**Comment by wangliang1989** [comment]
很多人似乎还不会找经纬度，是否考虑写个教程说明如何找经纬度
