### ISSUE TITLE
绘制符合出版要求的中国地图

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org.v1#22]
要求：
1. 数据有确切来源
2. 可通过审核

**Comment by wangliang1989** [comment]
http://219.238.166.215/mcp/MapProduct/Cut/%E4%B8%AD%E6%96%87%E6%94%BF%E5%8C%BA%E7%89%88/400%E4%B8%87%E6%94%BF%E5%8C%BA%E7%89%88/Map.htm
人工离散
